### PR TITLE
feat: enhance restrict_automount_sa_token

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

## Description

use =() syntax for serviceAccountAutoMountToken

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

### CODE REVIEW

**Comment by developer-guy** [comment]
cc: @chipzoller 🙋🏻‍♂️

**Comment by chipzoller** [comment]
I get the `"false"` format, but why the anchor? The purpose of this policy is to _enforce_ that `automountServiceAccountToken` is set to false, not only if it exists first.

**Comment by developer-guy** [comment]
ah okay, let me fix that.

**Comment by chipzoller** [comment]
I will also point out that I wrote this policy and it absolutely _did_ work at some point in the past.

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
