### PR TITLE
Code formatting for add-default-securitycontext.yaml and add digest field for every artifacthub-pkg.yml

### PR DESCRIPTION
**Pull request by guohaoyu110**
## Related Issue(s)
Close: https://github.com/kyverno/policies/issues/562
Close: https://github.com/kyverno/policies/issues/564

## Description
Code formatting for for add-default-securitycontext/add-default-securitycontext.yaml

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

### CODE REVIEW

**Review by chipzoller — CHANGES_REQUESTED** [review]
This doesn't address what I'm pointing out. See missing backtick on runAsUser.

**Comment by guohaoyu110** [comment]
> This doesn't address what I'm pointing out. See missing backtick on runAsUser.

i  see.

**Comment by guohaoyu110** [comment]
the script for adding digest field is something like this:

```
#!/bin/bash

# Loop through every artifacthub-pkg.yml file in the repository
for file in $(find . -name "artifacthub-pkg.yml"); do
    # Calculate the SHA256 hash of the file
    sha256=$(shasum -a 256 $file | cut -d' ' -f1)

    # Add the hash to the file in the format "digest: <hash>"
    echo "digest: $sha256" >> $file
done



```

**Review by chipzoller — APPROVED** [review]
Looks good.

**Comment by chipzoller** [comment]
@guohaoyu110 I didn't catch this until now. The digest in the `artifact-hub.pkg` file's `digest` field should be the digest of the POLICY and not that of the metadata file itself. Please address.

**Comment by guohaoyu110** [comment]
> @guohaoyu110 I didn't catch this until now. The digest in the `artifact-hub.pkg` file's `digest` field should be the digest of the POLICY and not that of the metadata file itself. Please address.

@chipzoller  does that mean i need to change all the digest value in all the metadata files since i made all of them wrong?

**Comment by chipzoller** [comment]
Yes, you will need to modify your script and re-run it to make the digest come from the policy.

**Pull request merged**
