### PR TITLE
Update the incorrect rulename

### PR DESCRIPTION
**Pull request by mohamedasifs123**
## Descriptions
Updating the incorrect rule name

## Checklist

- [] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

### CODE REVIEW

**Review by chipzoller — CHANGES_REQUESTED** [review]
Thanks for fixing this. Please see the [contribution guide](https://github.com/kyverno/policies?tab=readme-ov-file#contribution). You need to also recompute the hash and update `artifacthub-pkg.yml`. Please also leave the new line at the end of the file (L58).

**Comment by mohamedasifs123** [comment]
Can you please tell me how yo recompute the hash

**Comment by chipzoller** [comment]
On Linux use the `sha256sum` program.

**Comment by mohamedasifs123** [comment]
Thanks and for which file I need to generate?

**Comment by chipzoller** [comment]
The policy file which you updated.

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
