### PR TITLE
Validate Test Cases

### PR DESCRIPTION
**Pull request by oshi36**
SignedOff-by :   Oshi Gupta <oshiagupta36@gmail.com>
## Related Issue(s)
Partially addresses [#3121](https://github.com/kyverno/kyverno/issues/3121)

## Description
As a part of my LFX mentorship task, I am adding test cases and other manifests for the validate policies

#### Best-Practices Category 
- [check-deprecated-apis](https://github.com/kyverno/kyverno/pull/3439) 
Note: the above is an updated policy for checking deprecation APIs and not the existing one in this policy repo.

#### Other Category 

-  [advanced_restrict_image_registries](https://github.com/kyverno/policies/tree/main/other/advanced_restrict_image_registries)
- [allowed_label_changes](https://github.com/kyverno/policies/tree/main/other/allowed_label_changes)
- [block-images-with-volumes](https://github.com/kyverno/policies/tree/main/other/block_images_with_volumes)
- [block_large_images](https://github.com/kyverno/policies/tree/main/other/block_large_images)
- [block_stale_images](https://github.com/kyverno/policies/tree/main/other/block_stale_images)
- [check_nvidia_gpu](https://github.com/kyverno/policies/tree/main/other/check_nvidia_gpu)
- [disallow_all_secrets](https://github.com/kyverno/policies/tree/main/other/disallow_all_secrets)
- [enforce_resources_as_ratio](https://github.com/kyverno/policies/tree/main/other/enforce_resources_as_ratio)
- [ensure_readonly_hostpath](https://github.com/kyverno/policies/tree/main/other/ensure_readonly_hostpath)
- [exclude_namespaces_dynamically](https://github.com/kyverno/policies/blob/main/other/exclude_namespaces_dynamically.yaml)
- [ensure-production-matches-staging](https://github.com/kyverno/policies/tree/main/other/ensure-production-matches-staging)
- [ingress_host_match_tls](https://github.com/kyverno/policies/tree/main/other/ingress_host_match_tls)
- [limit-hostpath-vols](https://github.com/kyverno/policies/tree/main/other/limit-hostpath-vols)
- [only_trustworthy_registries_set_root](https://github.com/kyverno/policies/tree/main/other/only_trustworthy_registries_set_root)
- [require_emptydir_requests_limits](https://github.com/kyverno/policies/tree/main/other/require_emptydir_requests_limits)
- [require_unique_external_dns](https://github.com/kyverno/policies/tree/main/other/require_unique_external_dns)
- [restrict_service_port_range](https://github.com/kyverno/policies/tree/main/other/restrict_service_port_range)
- [require_netpol](https://github.com/kyverno/policies/blob/main/other/require_netpol.yaml)
- [require_pdb](https://github.com/kyverno/policies/blob/main/other/require_pdb.yaml)
- [require_image_source](https://github.com/kyverno/policies/tree/main/other/require_image_source)
- [restrict_service_account](https://github.com/kyverno/policies/blob/main/other/restrict_service_account.yaml)
- [restrict_secrets_by_label](https://github.com/kyverno/policies/tree/main/other/restrict_secrets_by_label)

#### Trafeik Category 
- [disallow_default_tlsoptions](https://github.com/kyverno/policies/blob/main/traefik/disallow_default_tlsoptions/disallow_default_tlsoptions.yaml)

Also, I have moved policies in the folder so that they will not be duplicated in rendering to the website and added the `kyverno.io/kyverno-version: 1.6.2` and `kyverno.io/kubernetes-version: "1.23"` in the polices where it was missing, after checking on the respective versions.

[Unique Ingress path policy for Other ](https://github.com/kyverno/policies/blob/main/other/unique-ingress-paths.yaml)category has [some issue](https://github.com/kyverno/kyverno/issues/3087) with kyverno CLI , so its test cases are not added in this.
## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

### CODE REVIEW

**Comment by chipzoller** [comment]
@oshi36 a couple of things if you please:
1. There are now conflicts that must be resolved.
2. Would you mark this as draft until you are finished with adding all necessary tests? This is so it is easier to review one time rather than tracking across scattered commits.

Thank you!

**Comment by oshi36** [comment]
Sure @chipzoller, I will resolve the conflicts.
Also, I have finished adding all the test cases from my side. But as you are suggesting I will mark it as draft.

**Comment by chipzoller** [comment]
Looks like tests are failing.

**Comment by chipzoller** [comment]
Conflicts to resolve here.

**Review by chipzoller — APPROVED** [review]
Thank you, Oshi, this will be of tremendous help in testing future code for regressions. A few of these policies were copied and not moved, but I will clean these up.

**Comment by oshi36** [comment]
Thank you @chipzoller for this.Looking forward to working more with your guidance.

**Pull request merged**
