### PR TITLE
chore: bump chainsaw to v0.2.3

### PR DESCRIPTION
**Pull request by eddycharly**
## Related Issue(s)

* Bump chainsaw to v0.2.2.
* Fixes CEL-related tests to be compatible with this version of Chainsaw.

### CODE REVIEW

**Comment by eddycharly** [comment]
cc @chipzoller all tests are green now

**Comment by chipzoller** [comment]
Supersedes #1026

**Comment by chipzoller** [comment]
Thank you, @eddycharly

**Comment by chipzoller** [comment]
Can bump to 0.2.3 now.

**Comment by eddycharly** [comment]
> Can bump to 0.2.3 now.

Done

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
