### PR TITLE
Fixed sample policies to include more container types

### PR DESCRIPTION
**Pull request by michaelkotelnikov**
## Related Issue(s)

Related to - https://github.com/kyverno/policies/issues/951

## Description

Fixes the samples polices described in the issue.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

### CODE REVIEW

**Comment by michaelkotelnikov** [comment]
@realshuting

**Comment by chipzoller** [comment]
Thanks. Minimally, we need you to update the artifacthub-pkg.yml file for every policy you modified. Please see the contribution guide in the root of this repo for details.

**Comment by michaelkotelnikov** [comment]
Thank you @chipzoller for pointing this out. Fixed now.

**Review by realshuting — APPROVED** [review]

**Review by chipzoller — COMMENTED** [review]
It'd be nice to include these additional container types in the automated Chainsaw tests.

**Pull request merged**
