### PR TITLE
Added test for limit-dnsnames

### PR DESCRIPTION
**Pull request by siddharthlal25**
Added resource and test for `limit-dnsnames` policy

### CODE REVIEW

**Comment by siddharthlal25** [comment]
@realshuting @chipzoller it would be really nice if you guys could review the PR.

**Comment by chipzoller** [comment]
Relevant Slack discussion to see if this PR is impacted: https://kubernetes.slack.com/archives/CLGR9BJU9/p1629222089357300

**Comment by realshuting** [comment]
@viveksahu26 - can you please help review this PR?

**Comment by viveksahu26** [comment]
@realshuting , can I review this PR.

**Comment by vyankyGH** [comment]
> @viveksahu26 - can you please help review this PR?

Sure..

**Comment by siddharthlal25** [comment]
When the length validation part was present in preconditions, the tests were failing. (Link to the [tests](https://github.com/siddharthlal25/policies/blob/slal-test/cert-manager/limit-dnsnames/test.yaml)). I placed the validating condition in `spec.rules.validate.deny` and the tests worked out!

**Review by NoSkillGirl — APPROVED** [review]

**Pull request merged**
