### PR TITLE
Add OpenShift policies

### PR DESCRIPTION
**Pull request by patelrit**
## Checklist

- [X] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [X] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

### CODE REVIEW

**Review by JimBugwadia — APPROVED** [review]

**Review by chipzoller — CHANGES_REQUESTED** [review]
As we are now trying to standardize on a few new annotations described [here](https://github.com/kyverno/policies/wiki/Kyverno-annotations), it would be appreciated if these policies can be marked with `kyverno.io/kyverno-version` and `kyverno.io/kubernetes-version`.

The `policies.kyverno.io/subject` is set to, if necessary, a comma-separate string of the resources in the match clause.

`policies.kyverno.io/category` here should always be `OpenShift`.

**Comment by patelrit** [comment]
Sure, will make the changes.

It would be great if these recommendations for annotations are reported by the kyverno test utility.

**Review by chipzoller — CHANGES_REQUESTED** [review]
Thank you, @patelrit , however I see that the last line from the [comment here](https://github.com/kyverno/policies/pull/279#pullrequestreview-898927362) doesn't appear to be fully addressed. Going forward for all new policies, because non-`any`|`all` `match`|`exclude` statements are deprecated, we'd like to ensure these blocks have one or the other even if it's just a single condition.

**Review by chipzoller — APPROVED** [review]
Thank you, @patelrit !

**Pull request merged**
