### PR TITLE
Create a new folder containing a policy which does correspond to the folder name but does not have an artifacthub-pkg.yml file.

### PR DESCRIPTION
**Pull request by guohaoyu110**
## Related Issue(s)
Close: https://github.com/kyverno/policies/issues/606

## Description
Create a new folder containing a policy which does correspond to the folder name but does not have an artifacthub-pkg.yml file.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

### CODE REVIEW

**Comment by guohaoyu110** [comment]
@chipzoller please review this test.

**Comment by chipzoller** [comment]
Good, test passes. Now add the file with the expected file name to ensure it passes CI.

**Comment by chipzoller** [comment]
Good, test is complete. Anything else left?

**Comment by guohaoyu110** [comment]
> Good, test is complete. Anything else left?

i think everything is done.

**Comment by guohaoyu110** [comment]
Thank you for all the guidance and contributions. @chipzoller

**Pull request closed without merging**
