### PR TITLE
Updated replace image registry

### PR DESCRIPTION
**Pull request by siddhikhapare**
## Related Issue(s)
#882 

## Description
Rewrite the image registry, to force all pulls through a proxy cache with using harbor

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

### CODE REVIEW

**Comment by siddhikhapare** [comment]
@JimBugwadia @chipzoller Could you please review my PR.

**Review by chipzoller — COMMENTED** [review]
Why are you modifying the existing policy? I don't think we need to do that; I think the idea was to add a new one rather than modify the current one.

**Comment by siddhikhapare** [comment]
> Why are you modifying the existing policy? I don't think we need to do that; I think the idea was to add a new one rather than modify the current one.

Sure. I'll make it happen. Thanks.

**Comment by chipzoller** [comment]
Converting to draft. Please mark as ready for review when complete.

**Pull request closed without merging**
