### PR TITLE
chore: remove k8s 1.24 and add k8s 1.28

### PR DESCRIPTION
**Pull request by eddycharly**
## Related Issue(s)

This PR removes k8s 1.24 and adds k8s 1.28 to the test grid.

### CODE REVIEW

**Comment by chipzoller** [comment]
I thought we wanted to still claim support for 1.24-1.28 but make this a per-version support statement.

**Comment by eddycharly** [comment]
@chipzoller you want to keep 1.24 ?

**Comment by chipzoller** [comment]
Slack thread for reference [here](https://kubernetes.slack.com/archives/C032MM2CH7X/p1692492488756089). I think the decision was to remove 1.24. If that's the case, I'm ok.

**Comment by eddycharly** [comment]
yeah, i think it would be aligned with what we did in the kyverno/kyverno repo.

**Pull request merged**
