### PR TITLE
policy helm chart initial seed

### PR DESCRIPTION
**Pull request by krisek**
This is the initial revision of  Helm chart that deploys Kyverno policies useful in multi-tenant environments.

Signed-off-by: Kristof Imre Szabo <kris@lxsystems.de>

### CODE REVIEW

**Comment by chipzoller** [comment]
@krisek thanks for this PR, however kyverno/policies is really intended for "loose" policies and not Helm charts. I haven't looked at everything, but are these taken from the existing policy samples or are some net new?

@realshuting your thoughts on how/if we can accept this?

**Comment by krisek** [comment]
The code is partially 

- 'remix' of policies already in the repo (with enhancements like implementing parameters), 
- completely new policies which I thought might be useful (namespace generation, certificate lifetime, etc.) and
- copy of policies in the repo (I think this are only the network related ones)  

On Helm or not Helm I cannot make a statement; in my use case we need to deploy parametrized policies on quite a few clusters, so I have barely other option than Helm.

**Comment by realshuting** [comment]
Hi @krisek - thanks for the PR!

@chipzoller - Kristof is willing to open source their Helm Chart that leverages Kyverno policies to build multitenant Kubernetes clusters, see repo https://github.com/szabo-kristof/multitenant-kyverno-rules.

Should we create a dedicated folder to add this Helm Chart or create a separate repo under the Kyveron organization?

cc @JimBugwadia

**Comment by krisek** [comment]
just to avoid any confusion: that account belongs to me as well, and the content of this PR and that repo is the same

**Comment by chipzoller** [comment]
The policy I'm seeing that would be good to come out of this is the certificate expiry check. But given that you've created a highly-specific set of curated policies for your operation (which is very nice!), I think we need to keep things a little more generic and loose and just support standalone policies as of now, because the [website ](https://kyverno.io/policies/) is not set up to process anything else currently.

**Comment by chipzoller** [comment]
My suggestion here is that we close this PR but would ask you to submit a new one just containing the [certificate expiry policy](https://github.com/szabo-kristof/multitenant-kyverno-rules/blob/main/multitenant-kyverno-rules/templates/certificate-expiry-max-100days.yaml) which is not templated for Helm.

**Comment by realshuting** [comment]
Thanks for sharing your thoughts @chipzoller !

@krisek - following up on the disucssion we had in the last Contributor meeting, also suggested by @JimBugwadia, we can:

1. Submit a separate PR to add these policies that are missing in our samples:
- [cert-manager-limit-dnsnames.yaml](https://github.com/krisek/policies/blob/policy_helm_chart/helm/multitenant-kyverno-rules/templates/cert-manager-limit-dnsnames.yaml)
- [certificate-expiry-max-100days.yaml](https://github.com/krisek/policies/blob/policy_helm_chart/helm/multitenant-kyverno-rules/templates/certificate-expiry-max-100days.yaml)
- [generate-default-access.yaml](https://github.com/krisek/policies/blob/policy_helm_chart/helm/multitenant-kyverno-rules/templates/generate-default-access.yaml)
- [generate-default-requests-limits.yaml](https://github.com/krisek/policies/blob/policy_helm_chart/helm/multitenant-kyverno-rules/templates/generate-default-requests-limits.yaml)

2. Add a section in the [resources](https://kyverno.io/resources/) called "More Sample Policies" and there we can add a link to your [repository](https://github.com/szabo-kristof/multitenant-kyverno-rules) and a description. We can also add links to the Flux2 policies, OpenEBS policies, etc.

3. If you are interested, we'd like to invite you to come and present / demo your policies in the next community meeting, it will be on Wednesday, October 20⋅9:00 – 10:00am PT.

What do you think?

**Comment by krisek** [comment]
Agreed, thanks for the feedback, I'll take care about the new PR, happy to showcase the rules.

**Pull request closed without merging**
