### PR TITLE
added tests for restrict-issuer policy

### PR DESCRIPTION
**Pull request by siddharthlal25**
Signed-off-by: siddharthlal25 <siddharthlal25@gmail.com>

### CODE REVIEW

**Comment by siddharthlal25** [comment]
@realshuting @chipzoller can you guys please review this PR.

**Review by chipzoller — CHANGES_REQUESTED** [review]
Looks good. Can you show Kyverno CLI test results with your PR, please?

**Comment by siddharthlal25** [comment]
Here are the test results:
```
Executing restrict-issuer...
applying 1 policy to 2 resources... 
│───│─────────────────────────────────────────────────────────────────────────────│────────│
│ # │ TEST                                                                        │ RESULT │
│───│─────────────────────────────────────────────────────────────────────────────│────────│
│ 1 │ letsencrypt-crt with cert-manager-restrict-issuer/restrict-corp-cert-issuer │ Pass   │
│ 2 │ acme-crt with cert-manager-restrict-issuer/restrict-corp-cert-issuer        │ Pass   │
│───│─────────────────────────────────────────────────────────────────────────────│────────│
```

**Review by realshuting — APPROVED** [review]

**Review by chipzoller — APPROVED** [review]

**Comment by chipzoller** [comment]
Thank you, @siddharthlal25 !

**Pull request merged**
