### PR TITLE
feat: add pod security standards (restricted) in CEL expressions - Part 3

### LINKED ISSUE #773: [Sample] Add policies using CEL expressions for Pod Security Standards
### Problem Statement

Kyverno now supports validating resources using CEL expressions. It'd be great to write policies for pod security standards in CEL.

### Solution Description

None

### Example "Good" Resource

_No response_

### Example "Bad" Resource

_No response_

### Other Comments

_No response_

### Slack discussion

_No response_

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

### PR DESCRIPTION
**Pull request by MariamFahmy98**
## Related Issue(s)

Closes #773

## Description
This PR adds Kyverno policies written in CEL expressions for pod security standards (restricted).

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

### CODE REVIEW

**Comment by chipzoller** [comment]
The `require-run-as-nonroot` policy here is failing kuttl tests.

**Comment by chipzoller** [comment]
Per Slack discussion, if `validate.message` does not work currently for CEL expression Kyverno policies, the field should be removed.

**Comment by MariamFahmy98** [comment]
Regarding the failed test `require-run-as-nonroot`, I got different results when using `kyverno test`.
1. In case of using `kyverno test` CLI, all tests pass as expected. (The same resources are used for kuttl tests as well):
```
Loading test  ( ../policies/pod-security-cel/restricted/require-run-as-nonroot/kyverno-test.yaml ) ...
  Loading values/variables ...
  Loading policies ...
  Loading resources ...
  Applying 1 policy to 75 resources ...
  Checking results ...

│──────────│────────────────────────│─────────────────│─────────────────────────────│────────│────────│
│ ID (75)  │ POLICY                 │ RULE            │ RESOURCE                    │ RESULT │ REASON │
│──────────│────────────────────────│─────────────────│─────────────────────────────│────────│────────│
│        1 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob01        │ Pass   │ Ok     │
│        2 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob02        │ Pass   │ Ok     │
│        3 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob03        │ Pass   │ Ok     │
│        4 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob04        │ Pass   │ Ok     │
│        5 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob05        │ Pass   │ Ok     │
│        6 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob06        │ Pass   │ Ok     │
│        7 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob07        │ Pass   │ Ok     │
│        8 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob08        │ Pass   │ Ok     │
│        9 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob09        │ Pass   │ Ok     │
│       10 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob10        │ Pass   │ Ok     │
│       11 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob11        │ Pass   │ Ok     │
│       12 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob12        │ Pass   │ Ok     │
│       13 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob13        │ Pass   │ Ok     │
│       14 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob14        │ Pass   │ Ok     │
│       15 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob15        │ Pass   │ Ok     │
│       16 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment01  │ Pass   │ Ok     │
│       17 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment02  │ Pass   │ Ok     │
│       18 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment03  │ Pass   │ Ok     │
│       19 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment04  │ Pass   │ Ok     │
│       20 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment05  │ Pass   │ Ok     │
│       21 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment06  │ Pass   │ Ok     │
│       22 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment07  │ Pass   │ Ok     │
│       23 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment08  │ Pass   │ Ok     │
│       24 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment09  │ Pass   │ Ok     │
│       25 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment10  │ Pass   │ Ok     │
│       26 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment11  │ Pass   │ Ok     │
│       27 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment12  │ Pass   │ Ok     │
│       28 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment13  │ Pass   │ Ok     │
│       29 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment14  │ Pass   │ Ok     │
│       30 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment15  │ Pass   │ Ok     │
│       31 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod01                │ Pass   │ Ok     │
│       32 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod02                │ Pass   │ Ok     │
│       33 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod03                │ Pass   │ Ok     │
│       34 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod04                │ Pass   │ Ok     │
│       35 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod05                │ Pass   │ Ok     │
│       36 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod06                │ Pass   │ Ok     │
│       37 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod07                │ Pass   │ Ok     │
│       38 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod08                │ Pass   │ Ok     │
│       39 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod09                │ Pass   │ Ok     │
│       40 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod10                │ Pass   │ Ok     │
│       41 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod11                │ Pass   │ Ok     │
│       42 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod12                │ Pass   │ Ok     │
│       43 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod13                │ Pass   │ Ok     │
│       44 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod14                │ Pass   │ Ok     │
│       45 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod15                │ Pass   │ Ok     │
│       46 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob01       │ Pass   │ Ok     │
│       47 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob02       │ Pass   │ Ok     │
│       48 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob03       │ Pass   │ Ok     │
│       49 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob04       │ Pass   │ Ok     │
│       50 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob05       │ Pass   │ Ok     │
│       51 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob06       │ Pass   │ Ok     │
│       52 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob07       │ Pass   │ Ok     │
│       53 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob08       │ Pass   │ Ok     │
│       54 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob09       │ Pass   │ Ok     │
│       55 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob10       │ Pass   │ Ok     │
│       56 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment01 │ Pass   │ Ok     │
│       57 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment02 │ Pass   │ Ok     │
│       58 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment03 │ Pass   │ Ok     │
│       59 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment04 │ Pass   │ Ok     │
│       60 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment05 │ Pass   │ Ok     │
│       61 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment06 │ Pass   │ Ok     │
│       62 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment07 │ Pass   │ Ok     │
│       63 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment08 │ Pass   │ Ok     │
│       64 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment09 │ Pass   │ Ok     │
│       65 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment10 │ Pass   │ Ok     │
│       66 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod01               │ Pass   │ Ok     │
│       67 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod02               │ Pass   │ Ok     │
│       68 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod03               │ Pass   │ Ok     │
│       69 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod04               │ Pass   │ Ok     │
│       70 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod05               │ Pass   │ Ok     │
│       71 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod06               │ Pass   │ Ok     │
│       72 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod07               │ Pass   │ Ok     │
│       73 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod08               │ Pass   │ Ok     │
│       74 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod09               │ Pass   │ Ok     │
│       75 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod10               │ Pass   │ Ok     │
│──────────│────────────────────────│─────────────────│─────────────────────────────│────────│────────│


Test Summary: 75 tests passed and 0 tests failed
``` 
2. In case of running it as a kuttl test, the following resources are created although it shouldn't:
    - `badpod01`
    - `badpod05`
    - `badpod13`
    - `baddeployment01`
    - `baddeployment05`
    - `baddeployment13`
    - `badcronjob01`
    - `badcronjob05`
    - `badcronjob13`

The main issue is in the second CEL expression. When I tried to remove it from the policy, the `kyverno test` fails but kuttl tests pass!
1. In case of using `kyverno test`: (there's a bug in the output!)
```
Loading test  ( ../policies/pod-security-cel/restricted/require-run-as-nonroot/kyverno-test.yaml ) ...
  Loading values/variables ...
  Loading policies ...
  Loading resources ...
  Applying 1 policy to 75 resources ...
  Checking results ...

│──────────│────────────────────────│─────────────────│─────────────────────────────│────────│─────────────────────│
│ ID (75)  │ POLICY                 │ RULE            │ RESOURCE                    │ RESULT │ REASON              │
│──────────│────────────────────────│─────────────────│─────────────────────────────│────────│─────────────────────│
│        1 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob01        │ Pass   │ Want fail, got pass │
│        2 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob02        │ Pass   │ Ok                  │
│        3 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob03        │ Pass   │ Ok                  │
│        4 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob04        │ Pass   │ Ok                  │
│        5 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob05        │ Pass   │ Want fail, got pass │
│        6 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob06        │ Pass   │ Ok                  │
│        7 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob07        │ Pass   │ Ok                  │
│        8 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob08        │ Pass   │ Ok                  │
│        9 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob09        │ Pass   │ Ok                  │
│       10 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob10        │ Pass   │ Ok                  │
│       11 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob11        │ Pass   │ Ok                  │
│       12 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob12        │ Pass   │ Ok                  │
│       13 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob13        │ Pass   │ Want fail, got pass │
│       14 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob14        │ Pass   │ Ok                  │
│       15 │ require-run-as-nonroot │ run-as-non-root │ CronJob/badcronjob15        │ Pass   │ Ok                  │
│       16 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment01  │ Pass   │ Want fail, got pass │
│       17 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment02  │ Pass   │ Ok                  │
│       18 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment03  │ Pass   │ Ok                  │
│       19 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment04  │ Pass   │ Ok                  │
│       20 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment05  │ Pass   │ Want fail, got pass │
│       21 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment06  │ Pass   │ Ok                  │
│       22 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment07  │ Pass   │ Ok                  │
│       23 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment08  │ Pass   │ Ok                  │
│       24 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment09  │ Pass   │ Ok                  │
│       25 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment10  │ Pass   │ Ok                  │
│       26 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment11  │ Pass   │ Ok                  │
│       27 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment12  │ Pass   │ Ok                  │
│       28 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment13  │ Pass   │ Want fail, got pass │
│       29 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment14  │ Pass   │ Ok                  │
│       30 │ require-run-as-nonroot │ run-as-non-root │ Deployment/baddeployment15  │ Pass   │ Ok                  │
│       31 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod01                │ Pass   │ Want fail, got pass │
│       32 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod02                │ Pass   │ Ok                  │
│       33 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod03                │ Pass   │ Ok                  │
│       34 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod04                │ Pass   │ Ok                  │
│       35 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod05                │ Pass   │ Want fail, got pass │
│       36 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod06                │ Pass   │ Ok                  │
│       37 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod07                │ Pass   │ Ok                  │
│       38 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod08                │ Pass   │ Ok                  │
│       39 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod09                │ Pass   │ Ok                  │
│       40 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod10                │ Pass   │ Ok                  │
│       41 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod11                │ Pass   │ Ok                  │
│       42 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod12                │ Pass   │ Ok                  │
│       43 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod13                │ Pass   │ Want fail, got pass │
│       44 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod14                │ Pass   │ Ok                  │
│       45 │ require-run-as-nonroot │ run-as-non-root │ Pod/badpod15                │ Pass   │ Ok                  │
│       46 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob01       │ Pass   │ Ok                  │
│       47 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob02       │ Pass   │ Ok                  │
│       48 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob03       │ Pass   │ Ok                  │
│       49 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob04       │ Pass   │ Ok                  │
│       50 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob05       │ Pass   │ Ok                  │
│       51 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob06       │ Pass   │ Ok                  │
│       52 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob07       │ Pass   │ Ok                  │
│       53 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob08       │ Pass   │ Ok                  │
│       54 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob09       │ Pass   │ Ok                  │
│       55 │ require-run-as-nonroot │ run-as-non-root │ CronJob/goodcronjob10       │ Pass   │ Ok                  │
│       56 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment01 │ Pass   │ Ok                  │
│       57 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment02 │ Pass   │ Ok                  │
│       58 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment03 │ Pass   │ Ok                  │
│       59 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment04 │ Pass   │ Ok                  │
│       60 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment05 │ Pass   │ Ok                  │
│       61 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment06 │ Pass   │ Ok                  │
│       62 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment07 │ Pass   │ Ok                  │
│       63 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment08 │ Pass   │ Ok                  │
│       64 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment09 │ Pass   │ Ok                  │
│       65 │ require-run-as-nonroot │ run-as-non-root │ Deployment/gooddeployment10 │ Pass   │ Ok                  │
│       66 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod01               │ Pass   │ Ok                  │
│       67 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod02               │ Pass   │ Ok                  │
│       68 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod03               │ Pass   │ Ok                  │
│       69 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod04               │ Pass   │ Ok                  │
│       70 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod05               │ Pass   │ Ok                  │
│       71 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod06               │ Pass   │ Ok                  │
│       72 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod07               │ Pass   │ Ok                  │
│       73 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod08               │ Pass   │ Ok                  │
│       74 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod09               │ Pass   │ Ok                  │
│       75 │ require-run-as-nonroot │ run-as-non-root │ Pod/goodpod10               │ Pass   │ Ok                  │
│──────────│────────────────────────│─────────────────│─────────────────────────────│────────│─────────────────────│


Test Summary: 75 tests passed and 0 tests failed
```
2. In case of running it as a kuttl test, it passes!

**Comment by chipzoller** [comment]
So is the second expression wrong? And is there one or two bugs here?

**Comment by MariamFahmy98** [comment]
The 2nd expression is required because it basically checks that either of `spec.securityContext.runAsNonRoot` or `spec.containers.runAsNonRoot`/`spec.initContainers.runAsNonRoot`/`spec.ephemeralContainers.runAsNonRoot` must be set to true.

For example, the following pod should fail:
```
apiVersion: v1
kind: Pod
metadata:
  name: badpod01
spec:
  containers:
  - name: container01
    image: busybox:1.35
```
The 1st expression will be evaluated to true, whereas the 2nd one will be evaluated to false so it is required.

The `kyverno test` result is expected but I haven't figured out why running the kuttl test fails! Actually, why we have two different results? I need to investigate in it.

**Comment by chipzoller** [comment]
Have you tried the CEL playground to make sure this is being evaluated correctly?

**Comment by chipzoller** [comment]
Were you able to get the last policy written?

**Comment by eddycharly** [comment]
@MariamFahmy98 `createdAt` is a required field in artifacthub-pkg.yaml files

**Comment by MariamFahmy98** [comment]
For testing purposes, I extracted the expression that causes failures into a separate policy and tested it against three bad pods. 
1. policy.yaml:
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-run-as-nonroot
spec:
  validationFailureAction: Enforce
  rules:
    - name: run-as-non-root
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        cel:
          expressions:
            - expression: >-
                has(object.spec.securityContext) ||
                (object.spec.containers.all(container, has(container.securityContext) && has(container.securityContext.runAsNonRoot))
                &&
                (!has(object.spec.initContainers) || object.spec.initContainers.all(container, has(container.securityContext) && has(container.securityContext.runAsNonRoot)))
                &&
                (!has(object.spec.ephemeralContainers) || object.spec.ephemeralContainers.all(container, has(container.securityContext) && has(container.securityContext.runAsNonRoot))))
              message: >-
                Running as root is not allowed. Either the field spec.securityContext.runAsNonRoot
                must be set to `true`, or the fields spec.containers[*].securityContext.runAsNonRoot,
                spec.initContainers[*].securityContext.runAsNonRoot, and spec.ephemeralContainers[*].securityContext.runAsNonRoot
                must be set to `true`.
```
2. resources.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: badpod01
  namespace: default
spec:
  containers:
  - name: container01
    image: busybox:1.35
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod05
spec:
  containers:
  - name: container01
    image: busybox:1.35
  - name: container02
    image: busybox:1.35
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod13
spec:
  initContainers:
  - name: initcontainer01
    image: busybox:1.35
  - name: initcontainer02
    image: busybox:1.35
  containers:
  - name: container01
    image: busybox:1.35
    securityContext:
      runAsNonRoot: true
```

Upon investigation, here is what I have discovered so far:
1. I tried to apply the policy using `kyverno apply` CLI , and all pods fail as expected:
```
summary:
  error: 0
  fail: 3
  pass: 0
  skip: 0
  warn: 0
```
2. I tried to run the policy in[ Kyverno playground](https://playground.kyverno.io/next/#/?content=N4IgDg9gNglgxgTxALhAQzDAagUwE4DOMEAdsgAQDWCAbviRAHTED0NAjADomUwkAmFAMJQArgQAu%2BAArR4CbgFscEtPzSrk3cuRJplFPDgCOomEYC0eUSQtoCFhiTwQIE7gTA44WkjpposOoSxCQAYmgwYkYAgnAhpBQAoiQAZhB4cDja5NZQOAS%2BOjoWuvo4hjZ2Dk5Wru5%2BxTqKGnAAFkVNxWgkCJ1d5KVGBBCimQX9A8W8AoU5U12lsvzzxQFBGhWrTVlQkwM4AB5gw0Skc40LJeRHJwVnZOQAfBbbVzpt9gAUEABGAFbeCSMTzeEHeMYwCQIISkKSHCQASnIAB8UW93j8AUCQV44Iw4HDIiR8ARGIEoF9CSRVHx8AAacifAhUol0vDguCQ6GwmlHJHkABkgqZ32ptJJHIIELwUJhcP5jGsJBiBAAcqQAEr1RGIjFXYX6hZfACEzKxgPiuLBfChvIlpORaPIf0twNB%2BNtEntxNJ5KglPFvrwjPNQfZnO58r5CORwtFLPDksjsp5CoRSpsqo1JG1bl1esu72KhqLxfIpvNrpxHsYODAbRwyjwgR97IITpRLuxVtr9cbzdbbMlZIprJpwdDYuH%2BBTcvt/LjIrDM6lMvn6eByuzWp1BaNXWUBAIaAA5hVnq8y8XNTYSHxT%2BR7Ll6uQYARdG4nwGIAB3HD8Iw5BJFCjZ4OQEiNuQqQwDgUD8OQtbSlyqbRvCW5Zuqu5uAeAyKOIEjkL8OCISoEEQOQAAGEjWDglGMhkEFQTBcH8B%2BtZJqSADaABUAC6c5pjGGEqlhub1PSuFdLWXptiOvECchUYLhm25iXmEiMj0CF9g2Tb4EOE7tgpgloYqak5hpUlNPhkhESR0qERIFHUbRlGMNwID0iAwyjOMKDoJguCEKEFAcNwMyCOQyxKCoagaGgnR6AYRFqJA/AAAxcCQHqdJxhCdKUyUXvlWWrDALTnhQvziAgvwQIcyDsIwADMACs3AWF13AYNgpKheQ4U8HwUUxSQyiqMEiU5MV1VpRAmUdTleJ5auFzXLN5CldlTQVWeF41QQdUNU1rVLRt5QUKVABM5WVQdtX1Y1zXtZ13V6EF/WJIN2WRRQY0TfFmgzZdqX8Ol7AtR4K05LJa2FWUKVettd37dVj0nS952DIjF7I6uGW3UWe1VURGPPWdOT5etOObSjxP3ejR1Padr1FkpqEqRI%2By5Jhln1BQNGiNkJBeSA0D8JqBR%2BVkAVi1ykgQIoUsjGMWQACI4DB94JDlcveXAYiSPgKsywUAW9cFDxhb9I0UAAyt4RgNIDU1JaDRinnARgrI0xWeGgWQUPwWtoKIUANNCXgUAA8mAaCmCLbs5PHx6/hkUUALIAOoAJoIAAWurYRQJnigAKrXWq12aooYtHFkYC6wQcsAL5AA==) and all pods fail as we expect.
3. I tried to apply both policy and resource in the cluster and all pods were created. This is the main issue.
4. I tried the CEL expression itself in the [CEL playground ](https://playcel.undistro.io/?content=H4sIAAAAAAAAA71UXWvbMBT9K7c2tAmk7rqxF7%2BFkjFG1pW2owz8oji3sYZ8ZSQ5TVj333elOHbSNsnKWCE4ku%2FHOUe6x7%2BiqXAiSqMYPqNBkBZcwX9U1Q58iJfwY%2Fh1DNrAl5tvl3CvTSlcklFGcQyfpLEORgtRVgoz0pOfmLs0IwBbYR4WALkmJyShsc0LgFMgUWLahd6dr0MAshQzjk1qu5zoRXqefPjYBQPsDXLhtMONoUWOocWO4Rl6DHvw18EdDHbXvj9YG1jfFtL8JWlJ0l3sI%2B4T%2FoX8dv1hAf%2FpLFk25rWRbunV4sKlmzEAU9PQXmq61tql4EzN5xYNIlxUBq2Vmnh0z87gDlWuSwSnw%2FhejMZwpcRyZnRN06OMOGX7nR90QXwKDo3InZwj95gMrcVyopZQ6Qd2wxSQ5tJoKpGc782wSrNLBDfgNRoZIg%2FSFStcXZaa%2BIbX7GAsaFazfugxfj%2FxTAKbU7hj0QhLXZtArVMEBUM3Sd8thsbCoAAO%2BbWVU%2FQu3DDpYIdLmy5XvjOcXNd0ElTMharFDnAx4ytkS29%2FBZpGo0a%2Fr8u1Ujy8vkbfc4cw1LYhZitphI%2F5yS%2BE7a0mPfEznjy58T5b%2BvGRH72VyTdTu3lLhFK9djsA37TdPm95fLw%2FI9kcrH5%2FhcxFq0Wv%2B9wcPWW%2F7cw%2BdKlBxHqzu%2BQtlLSCDuvBqsCSTaBeKeqFujdSxr%2Fo9x9krv0vuQYAAA%3D%3D) to check the result and the expression was evaluated to `false` aganist all pods.
5. I tried to create the VAP and its binding to check the policy results as well and pods were created.

Conclustion:
1. The expression is evaluated to false in the CEL playground which means the expression is correct.
2. The bad pods fail as expected in the Kyverno CLI and playground.
3. The bad pods were created successfully as a result of applying Kyverno policy and VAP.

I started a discussion thread in #sig-api-machinery-cel to see why VAP fails to block the creation of the pod.

**Comment by chipzoller** [comment]
Are we close to getting this in?

**Comment by chipzoller** [comment]
Ping @MariamFahmy98

**Review by JimBugwadia — APPROVED** [review]

**Comment by JimBugwadia** [comment]
@chipzoller - any additional comments or feedback?

**Review by chipzoller — CHANGES_REQUESTED** [review]
The value of the `policies.kyverno.io/category` annotation should be `Pod Security Standards (Restricted) in CEL` to be consistent with the [CEL Baseline policies](https://kyverno.io/policies/?policytypes=Pod%2520Security%2520Standards%2520%28Baseline%29%2520in%2520CEL)

**Review by JimBugwadia — APPROVED** [review]

**Review by chipzoller — CHANGES_REQUESTED** [review]
Apologies for missing this earlier and requesting more changes, but I also see the annotation `policies.kyverno.io/minversion: 1.11.0` is missing from these while it is present on the other CEL policies for PSS.

**Review by JimBugwadia — APPROVED** [review]

**Comment by JimBugwadia** [comment]
@chipzoller - anything else required to merge this?

**Review by chipzoller — APPROVED** [review]
LGTM. Nice job, @MariamFahmy98!

**Pull request merged**
