### PR TITLE
Add tests for pdb-minavailable policy

### PR DESCRIPTION
**Pull request by poblahblahblah**
## Description

Adds tests for the pdb-minavailable policy

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

### CODE REVIEW

**Comment by chipzoller** [comment]
Tests failing.

**Comment by poblahblahblah** [comment]
@chipzoller the failures look related to the `replace-image-registry` tests.

**Comment by chipzoller** [comment]
Can you retrigger this as well, please?

**Review by chipzoller — APPROVED** [review]
Thanks!

**Pull request merged**
