### PR TITLE
 Create policy for disallow empty ingress host

### PR DESCRIPTION
**Pull request by Anita-ihuman**
Signed-off-by: Anita-ihuman <charlesanita403@gmail.com>

### CODE REVIEW

**Comment by realshuting** [comment]
@Anita-ihuman - I updated the results in `test.yaml` and verified with the latest build, It works:

Here's my test.yaml, and I just realized for a deny rule, the `result` expects the actual result of the resource creation. So the first result is `pass` which means the resource is allowed to be created.
```yaml
results:
  - policy: disallow-empty-ingress-host
    rule: disallow-empty-ingress-host
    resource: ingress-wildcard-host
    result: pass
  - policy: disallow-empty-ingress-host
    rule: disallow-empty-ingress-host
    resource: minimal-ingress
    result: fail
```

```
✗ ./cmd/cli/kubectl-kyverno/kyverno test ./test-cli

Executing disallow_empty_ingress_host...
applying 1 policy to 2 resources... 
│───│─────────────────────────────│─────────────────────────────│───────────────────────│────────│
│ # │ POLICY                      │ RULE                        │ RESOURCE              │ RESULT │
│───│─────────────────────────────│─────────────────────────────│───────────────────────│────────│
│ 1 │ disallow-empty-ingress-host │ disallow-empty-ingress-host │ ingress-wildcard-host │ Pass   │
│ 2 │ disallow-empty-ingress-host │ disallow-empty-ingress-host │ minimal-ingress       │ Pass   │
│───│─────────────────────────────│─────────────────────────────│───────────────────────│────────│
```

**Comment by realshuting** [comment]
And here's an example of how you can define the `request.operation` variable for a particular rule:
https://github.com/kyverno/policies/blob/c61d92dddcfbb016a2ed4cd2c439f3b437436e74/other/block_updates_deletes/values.yaml

**Comment by realshuting** [comment]
@vyankyGH - can you help review this PR? We need to test with the latest CLI from kyverno/kyverno.

**Comment by vyankyGH** [comment]
Works for me too.

**Review by vyankyGH — APPROVED** [review]

**Pull request merged**
