### PR TITLE
Minor fixes for JSON patch policies

### PR DESCRIPTION
**Pull request by chipzoller**
## Description

Fixes and improves some JSON patch policies.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

### CODE REVIEW

**Comment by eddycharly** [comment]
@chipzoller why do we need to disable autogen ?

**Comment by chipzoller** [comment]
It was due to #4731.

**Comment by eddycharly** [comment]
But this is fixed now right ?

**Comment by chipzoller** [comment]
It's fixed in main but not in alpha.2, which is what I was testing against. I thought it wouldn't be bad to leave it enabled in these policies for now.

**Review by eddycharly — APPROVED** [review]

**Comment by eddycharly** [comment]
Ok but I really want to fix that, we should be able to support json patches but we need to revisit our autogen approach.

**Comment by chipzoller** [comment]
Ok, so what do you want me to do here? Re-enable autogen?

**Comment by eddycharly** [comment]
Nope, I approved. We will want to enable again when we support autogen with json patches.

**Pull request merged**
