### PR TITLE
Add pdb checks

### PR DESCRIPTION
**Pull request by andrewhibbert**
## Description

Description of these policies:
* require-reasonable-pdbs
  * This checks PDBs and cross-references deployments/statefulsets/replicas if they are present
   * If percentages are used it will check that `minAvailable` is between 1 and 50% or `maxUnavailable` is between 50 and 100%
   * If numbers are used it will check that minAvailable is less than the number of corresponding replicas in a deployment/statefulset/replicaset. There is a precondition of replicas greater than 1
   * If numbers are used it will check that maxUnavailable does not equal 0
* require-replicas-allow-disruption
   * This checks deployments/statefulsets/replicas and cross references PDBs if they are available
   * If numbers are used it checks to see that replicas are not less than or equal to PDB `minAvailable`. There is a precondition of replicas greater than 1

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

### CODE REVIEW

**Comment by chipzoller** [comment]
Tests are failing here.

**Comment by andrewhibbert** [comment]
The tests for these policies are passing:

```
│────│─────────────────────────│───────────────────────────────────────────────────│────────────────────────────────────────────────────────────────────────────────────│────────│
│ #  │ POLICY                  │ RULE                                              │ RESOURCE                                                                           │ RESULT │
│────│─────────────────────────│───────────────────────────────────────────────────│────────────────────────────────────────────────────────────────────────────────────│────────│
│  1 │ require-reasonable-pdbs │ require-resonable-pdb-percentage                  │ /PodDisruptionBudget/require-resonable-pdb-percentage-bad                          │ Pass   │
│  2 │ require-reasonable-pdbs │ require-resonable-pdb-percentage                  │ /PodDisruptionBudget/require-resonable-pdb-percentage-good                         │ Pass   │
│  3 │ require-reasonable-pdbs │ deployment-replicas-higher-than-pdb-minAvailable  │ default/PodDisruptionBudget/deployment-replicas-higher-than-pdb-minAvailable-bad   │ Pass   │
│  4 │ require-reasonable-pdbs │ deployment-replicas-higher-than-pdb-minAvailable  │ default/PodDisruptionBudget/deployment-replicas-higher-than-pdb-minAvailable-good  │ Pass   │
│  5 │ require-reasonable-pdbs │ statefulset-replicas-higher-than-pdb-minAvailable │ default/PodDisruptionBudget/statefulset-replicas-higher-than-pdb-minAvailable-bad  │ Pass   │
│  6 │ require-reasonable-pdbs │ statefulset-replicas-higher-than-pdb-minAvailable │ default/PodDisruptionBudget/statefulset-replicas-higher-than-pdb-minAvailable-good │ Pass   │
│  7 │ require-reasonable-pdbs │ replicaset-replicas-higher-than-pdb-minAvailable  │ default/PodDisruptionBudget/replicaset-replicas-higher-than-pdb-minAvailable-bad   │ Pass   │
│  8 │ require-reasonable-pdbs │ replicaset-replicas-higher-than-pdb-minAvailable  │ default/PodDisruptionBudget/replicaset-replicas-higher-than-pdb-minAvailable-good  │ Pass   │
│  9 │ require-reasonable-pdbs │ pdb-maxUnavailable-zero                           │ default/PodDisruptionBudget/pdb-maxUnavailable-zero-bad                            │ Pass   │
│ 10 │ require-reasonable-pdbs │ pdb-maxUnavailable-zero                           │ default/PodDisruptionBudget/pdb-maxUnavailable-zero-good                           │ Pass   │
│────│─────────────────────────│───────────────────────────────────────────────────│────────────────────────────────────────────────────────────────────────────────────│────────│

Executing require-replicas-allow-disruption...
applying 1 policy to 2 resources... 

│───│───────────────────────────────────│──────────────────────────────────────│──────────────────────────────────────────────────────────────│────────│
│ # │ POLICY                            │ RULE                                 │ RESOURCE                                                     │ RESULT │
│───│───────────────────────────────────│──────────────────────────────────────│──────────────────────────────────────────────────────────────│────────│
│ 1 │ require-replicas-allow-disruption │ replicas-allow-voluntary-disruptions │ default/Deployment/replicas-allow-voluntary-disruptions-good │ Pass   │
│ 2 │ require-replicas-allow-disruption │ replicas-allow-voluntary-disruptions │ default/Deployment/replicas-allow-voluntary-disruptions-bad  │ Pass   │
│───│───────────────────────────────────│──────────────────────────────────────│──────────────────────────────────────────────────────────────│────────│
```

**Comment by chipzoller** [comment]
Sorry, we have other tests failing due to code changes.

**Comment by chipzoller** [comment]
It looks like you do need to sign your commits though.

**Comment by chipzoller** [comment]
@andrewhibbert ☝️

**Comment by chipzoller** [comment]
@andrewhibbert ?

**Comment by andrewhibbert** [comment]
I've checked `replace-image-registry` and I can't see any reason why the changes I've made would cause that to fail. I've also run the tests locally and they all pass okay

**Comment by chipzoller** [comment]
Alright, sorry it's been so long, but I would like to try and get this in. I am just having difficulty fully understanding the first one. Plus, there are some other changes that need to be made to bring these into alignment with current library standards. In addition, since we are now listing policies on Artifact Hub, we have some dependencies there. I think it would be easier to open a new PR with these changes so we can discuss. Would you be ok with that?

**Comment by erikgb** [comment]
@andrewhibbert Have you abandoned this PR? Some of your work seems relevant in resolving https://github.com/kyverno/policies/issues/801.

**Comment by chipzoller** [comment]
Superseded by #920. Thank you for your contribution.

**Pull request closed without merging**
