### PR TITLE
Use actions/checkout to clone Kyverno

### PR DESCRIPTION
**Pull request by cbandy**
## Related Issue(s)

Related to #243 

## Description

Replace the parsing of environment variables and `git clone` with arguments to the `actions/checkout` action.

The action logs the commit hash as its final output. The last group in the log can be expanded to see the referenced branch. For example, a run on a push to the `release-1.7` branch shows:

```
Checking out the ref
  /usr/bin/git checkout --progress --force -B release-1.7 refs/remotes/origin/release-1.7
  Switched to a new branch 'release-1.7'
  branch 'release-1.7' set up to track 'origin/release-1.7'.

/usr/bin/git log -1 --format='%H'
'db440c1b10d91c29d0e28f279705d248ced5c4a7'
```

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

### CODE REVIEW

**Comment by chipzoller** [comment]
Thanks for this contribution. We require DCO sign-off if you can re-sign and do a force push.

**Comment by cbandy** [comment]
Done!

**Comment by cbandy** [comment]
Sorry to do this after you've already looked at this PR, but I added one more commit that changes the command to run Kyverno. It should be slightly more resilient to changes in the upstream project. 🙇🏻

**Review by chipzoller — APPROVED** [review]
Thanks!

**Pull request merged**
