### PR TITLE
change any namespace vars to request.namespace

### PR DESCRIPTION
**Pull request by chipzoller**
Signed-off-by: Chip Zoller <chipzoller@gmail.com>

## Related issue

Issue [2689 ](https://github.com/kyverno/kyverno/issues/2689) and discussion [2690](https://github.com/kyverno/kyverno/discussions/2690).

## What type of PR is this

/kind bug
## Proposed Changes

This PR updates two policies to use `request.namespace` for deriving the Namespace of an object as a replacement for the less optimal (and problematic) `request.object.metadata.namespace`. This actually fixes the policies to work properly for higher-level Pod controllers whereas the were silently broken (and apparently untested).

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [] I have added tests that prove my fix is effective or that my feature works.
- [] My PR contains new or altered behavior to Kyverno and
  
  - [] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.

### CODE REVIEW

**Review by realshuting — APPROVED** [review]

**Comment by MarcelMue** [comment]
@chipzoller This change breaks tests in https://github.com/kyverno/kyverno with 99% certainty.
```
 Executing allowed-podpriorities...
applying 1 policy to 3 resources... 

│───│───────────────────────│───────────────────────────────│─────────────────────────────│────────│
│ # │ POLICY                │ RULE                          │ RESOURCE                    │ RESULT │
│───│───────────────────────│───────────────────────────────│─────────────────────────────│────────│
│ 1 │ allowed-podpriorities │ validate-pod-priority-pods    │ default/Pod/myapp-pod       │ Fail   │
│ 2 │ allowed-podpriorities │ validate-pod-priority         │ default/Deployment/mydeploy │ Fail   │
│ 3 │ allowed-podpriorities │ validate-pod-priority-cronjob │ default/CronJob/hello       │ Fail   │
│───│───────────────────────│───────────────────────────────│─────────────────────────────│────────│
```
This run succeeded previously a few hours ago, now failed on a rerun:
https://github.com/kyverno/kyverno/runs/4155177355

**Comment by chipzoller** [comment]
Crap. Is `request.namespace` not supported in the CLI? cc @NoSkillGirl @viveksahu26

**Comment by chipzoller** [comment]
I know this works in the webhook because I tested it.

**Comment by MarcelMue** [comment]
> Crap. Is `request.namespace` not supported in the CLI? cc @NoSkillGirl @viveksahu26

I don't think it should work in the CLI AFAIK it's not populated there.

**Comment by MarcelMue** [comment]
It can probably be fixed with the values file?

**Comment by chipzoller** [comment]
Ok, let me fix.

**Comment by chipzoller** [comment]
PR send in #172

**Pull request merged**
