### PR TITLE
Test error when creating a new folder with a name which includes underscores.

### PR DESCRIPTION
**Pull request by guohaoyu110**
## Related Issue(s)
Close: https://github.com/kyverno/policies/issues/604

## Description
Test error when creating a new folder with a name which includes underscores.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

### CODE REVIEW

**Comment by guohaoyu110** [comment]
it generates the error as expected. @chipzoller 
Screenshot 2023-05-22 at 3 56 45 PM

**Comment by guohaoyu110** [comment]
Should i delete the change after this or modify the change to make it compatible with the workflow and all the checks?

**Comment by chipzoller** [comment]
Try a test where you rename only the policy file but leave the folder with underscores.

**Comment by guohaoyu110** [comment]
> Try a test where you rename only the policy file but leave the folder with underscores.
the folder is originally dashes i think, so you mean change both the policy file and the folder name to underscore?

**Comment by chipzoller** [comment]
This should be a net new folder. According to your files, both your folder name and your policy name is invalid. Change one of them and see the result.

**Comment by chipzoller** [comment]
Failed. Good. Now swap the two: change folder name so it's compliant but policy name so it is not.

**Comment by guohaoyu110** [comment]
> Failed. Good. Now swap the two: change folder name so it's compliant but policy name so it is not.

swapped already.

**Comment by chipzoller** [comment]
Check fails as intended so this is good. You're ready to do the other tests now.

**Comment by guohaoyu110** [comment]
> Check fails as intended so this is good. You're ready to do the other tests now.

should i change the files to merge this or i just close this pr and delete the test folder?

**Comment by chipzoller** [comment]
Close this PR and open a new one which tests the next scenario. There will be no files merged in any of these test PRs. The goal is to see failure everywhere we expect it, and success only when we expect it.

**Comment by guohaoyu110** [comment]
> Close this PR and open a new one which tests the next scenario. There will be no files merged in any of these test PRs. The goal is to see failure everywhere we expect it, and success only when we expect it.

understand, thank you.

**Pull request closed without merging**
