### PR TITLE
FIX: disable default enforcement of pod-security policies

### PR DESCRIPTION
**Pull request by bpereto**
## Related Issue(s)

#258 

## Description

change the behaviour of kustomize on psp-security policies for `validationFailureAction` to default "audit" as described in the readme:
> For validate rules, please set validationFailureAction: audit so that should a user download and apply the policy without having a yet full understanding of Kyverno, it will not cause unintended harm to their environment by blocking resources.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [ ] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

### CODE REVIEW

**Comment by chipzoller** [comment]
@JimBugwadia this PR removes the patch that set these in `enforce` mode, which is how it was pre my deletion. Do you want to go with this?

**Comment by JimBugwadia** [comment]
Can we update the docs to provide both options?
1. Command line to install with audit mode; and
2. Command line to install with enforce mode

Users can then choose what works best for them. 

The challenge we have had with only the audit mode, is that some users try and expect the pods to be blocked.

**Comment by chipzoller** [comment]
What would those commands be when using Kustomize? Would it entail accepting this PR or leaving the files as-is?

**Comment by JimBugwadia** [comment]
No, we would need to create 2 separate Kustomization files (we can move to folders like `enforce` and `audit`) one with the patch and one without. 

For audit policies the Kustomization is simply to combine all the files as no patches are applied.

**Comment by chipzoller** [comment]
So this structure and files look like this below?

pod-security/baseline/audit/kustomization.yaml 

```yaml
resources:
  - ../disallow-capabilities/disallow-capabilities.yaml
  - ../disallow-host-namespaces/disallow-host-namespaces.yaml
  - ../disallow-host-path/disallow-host-path.yaml
  - ../disallow-host-ports/disallow-host-ports.yaml
  - ../disallow-host-process/disallow-host-process.yaml
  - ../disallow-privileged-containers/disallow-privileged-containers.yaml
  - ../disallow-proc-mount/disallow-proc-mount.yaml
  - ../disallow-selinux/disallow-selinux.yaml
  - ../restrict-apparmor-profiles/restrict-apparmor-profiles.yaml
  - ../restrict-seccomp/restrict-seccomp.yaml
  - ../restrict-sysctls/restrict-sysctls.yaml
```

pod-security/baseline/enforce/kustomization.yaml 

```yaml
resources:
  - ../disallow-capabilities/disallow-capabilities.yaml
  - ../disallow-host-namespaces/disallow-host-namespaces.yaml
  - ../disallow-host-path/disallow-host-path.yaml
  - ../disallow-host-ports/disallow-host-ports.yaml
  - ../disallow-host-process/disallow-host-process.yaml
  - ../disallow-privileged-containers/disallow-privileged-containers.yaml
  - ../disallow-proc-mount/disallow-proc-mount.yaml
  - ../disallow-selinux/disallow-selinux.yaml
  - ../restrict-apparmor-profiles/restrict-apparmor-profiles.yaml
  - ../restrict-seccomp/restrict-seccomp.yaml
  - ../restrict-sysctls/restrict-sysctls.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/validationFailureAction
        value: enforce
    target:
      kind: ClusterPolicy
```

pod-security/restricted/audit/kustomization.yaml 

```yaml
bases:
  - ../../baseline
  
resources:
  - ../disallow-capabilities-strict/disallow-capabilities-strict.yaml
  - ../disallow-privilege-escalation/disallow-privilege-escalation.yaml
  - ../require-run-as-non-root-user/require-run-as-non-root-user.yaml
  - ../require-run-as-nonroot/require-run-as-nonroot.yaml
  - ../restrict-seccomp-strict/restrict-seccomp-strict.yaml
  - ../restrict-volume-types/restrict-volume-types.yaml
```

pod-security/restricted/enforce/kustomization.yaml

```yaml
bases:
  - ../../baseline
  
resources:
  - ../disallow-capabilities-strict/disallow-capabilities-strict.yaml
  - ../disallow-privilege-escalation/disallow-privilege-escalation.yaml
  - ../require-run-as-non-root-user/require-run-as-non-root-user.yaml
  - ../require-run-as-nonroot/require-run-as-nonroot.yaml
  - ../restrict-seccomp-strict/restrict-seccomp-strict.yaml
  - ../restrict-volume-types/restrict-volume-types.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/validationFailureAction
        value: enforce
    target:
      kind: ClusterPolicy
```

Note I have not actually tried to create any of this.

**Comment by JimBugwadia** [comment]
Yes, this seems right.

**Comment by chipzoller** [comment]
Turns out Kustomize will not allow this pattern because of security concerns. The error it'll return is something like:

```sh
$ kustomize build ./pod-security/restricted/enforce | kubectl apply -f -
Error: accumulating resources: accumulation err='accumulating resources from '../disallow-capabilities-strict/disallow-capabilities-strict.yaml': security; file '/mnt/c/Users/Chip/Documents/My Git/kyvernopolicies/pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict.yaml' is not in or below '/mnt/c/Users/Chip/Documents/My Git/kyvernopolicies/pod-security/restricted/enforce'': got file 'disallow-capabilities-strict.yaml', but '/mnt/c/Users/Chip/Documents/My Git/kyvernopolicies/pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict.yaml' must be a directory to be a root
error: no objects passed to apply
```

Not being a Kustomize expert, and not wanting to spend a tremendous amount of time on this, is there another option or should we just change the default `kustomization.yaml` files in `baseline` and `restricted` to remove the patch that sets them in `enforce` mode to align with how we've set them up with Helm? Helm definitely has a leg up on Kustomize in this regard as we don't need to fool with multiple `kustomization.yaml` files and directories.

**Comment by JimBugwadia** [comment]
I will take a look and propose a structure that works with kustomize.

**Comment by JimBugwadia** [comment]
I added an `enforce` directory at the same level as `baseline` and `restricted` and moved the patch there:

**audit**

```
kustomize build pod-security
```

**enforce**

```
kustomize build pod-security/enforce
```

**Review by chipzoller — APPROVED** [review]

**Comment by JimBugwadia** [comment]
@chipzoller - looks like this was merged. Shall we close the issue, or is there more needed here?

**Pull request merged**
