### PR TITLE
Add digest and make readme visiable in artifact hub

### PR DESCRIPTION
**Pull request by guohaoyu110**
## Related Issue(s)

https://github.com/kyverno/policies/pull/545
https://github.com/kyverno/policies/issues/549

## Description

Add digest in the artifacthub-pkg.yml, so that it can show updates in policies in artifact hub. 

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

### CODE REVIEW

**Comment by guohaoyu110** [comment]
the command is in every folder, type shasum -a 256 artifacthub-pkg.yml

**Comment by guohaoyu110** [comment]
@chipzoller  please review, thank you.

**Review by chipzoller — APPROVED** [review]

**Comment by chipzoller** [comment]
Thanks. In the future, please use GitHub's [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to link a PR to an issue(s) which it addresses so the issue closes automatically when the PR is merged.

**Comment by guohaoyu110** [comment]
> Thanks. In the future, please use GitHub's [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to link a PR to an issue(s) which it addresses so the issue closes automatically when the PR is merged.

Thanks, understand.

**Pull request merged**
