### PR TITLE
chore: check test files are up to date

### PR DESCRIPTION
**Pull request by eddycharly**
## Related Issue(s)

This PR checks test files are up to date.

### CODE REVIEW

**Review by chipzoller — COMMENTED** [review]
I need some more explanation on this one if you can provide.

**Comment by eddycharly** [comment]
@chipzoller i added a CLI command `kyverno fix test` that automatically updates test files:
- removes usage of deprecated fields
- compresses results
- ensures test has a name

This job makes sure that running the command does not change test files in the repo (they are up to date).

**Comment by chipzoller** [comment]
Ok, so is this expected to produce a failure if a diff is found?

**Comment by eddycharly** [comment]
Yep, in case of a failure you have to run `kyverno fix test . --save --compress` and push the changes.

**Comment by eddycharly** [comment]
I'm thinking about adding a `Makefile` to make this easier 🤷

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
