### PR TITLE
Deny Secret Service Account Token Type

### LINKED ISSUE #819: [Sample] policies to audit and restrict long-lived tokens for service accounts
### Problem Statement

Prior to v1.24, Kubernetes generated long lived service accounts by default. These pose a security risk.

### Solution Description

Sample policies to:
* audit for secrets with `type: kubernetes.io/service-account-token`
* audit for service accounts with any `secrets.name` configured
* enforce pod `automountServiceAccountToken: false`

### Example "Good" Resource

_No response_

### Example "Bad" Resource

_No response_

### Other Comments

See:
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
- https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/
- https://eng.d2iq.com/blog/service-account-tokens-in-kubernetes-v1.24/

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1701451535229319

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

### PR DESCRIPTION
**Pull request by swastik959**
## Related Issue(s)
partially closes #819 

## Description
added a sample policy to Deny Secret Service Account Token Type

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

### CODE REVIEW

**Comment by swastik959** [comment]
@chipzoller sure will add them soon

**Comment by siddhikhapare** [comment]
@swastik959 I have passed my tests you can use this in your policy, it will work 
```yaml
preconditions:
      all:
      - key: "{{ request.object.type}}"
        operator: Equals
        value: "kubernetes.io/service-account-token"
    validate:
      message: "Auto-mounting of Service Account tokens is not allowed to avoid getting long lived tokens."
      pattern:
          automountServiceAccountToken: "false"
```

**Comment by swastik959** [comment]
@siddhikhapare the tests is failing because artifacthub-pkg is not present . The policy I have written deals with the type object in a secret which should not be equal to ``kubernetes.io/service-account-token`` . you can complete this one only if you want . I can co-author you

**Comment by siddhikhapare** [comment]
@swastik959  see write test for pod not for secret will work 
volumepod

**Comment by siddhikhapare** [comment]
> kubernetes.io/service-account-token

@swastik959 policy regarding audit secret with type kubernetes.io/service-account-token which have long lived or short lived token. Even if preconditions do not write then it is identifying serviceaccount token and it will check expiration time of token provided or not.

**Comment by chipzoller** [comment]
Please follow PR template checklist and rename PR title to something more descriptive. These are general processes you should follow for every project and not Kyverno specific.

**Comment by swastik959** [comment]
@chipzoller actually I haven't added the chainsaw test so I was gonna do that after adding them

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
