### PR TITLE
Test whether generate error when creating a new folder with a name which includes underscores.

### PR DESCRIPTION
**Pull request by guohaoyu110**
## Related Issue(s)
Close: https://github.com/kyverno/policies/issues/604

## Description
test error when creating a new folder with a name which includes underscores.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

### CODE REVIEW

**Comment by guohaoyu110** [comment]
i updated the workflow file and delete an unnecessary file, and it can now produce the error i want to see in this test section.
Screenshot 2023-05-12 at 1 19 57 PM

**Comment by chipzoller** [comment]
I didn't catch this until now. Move the new step before "Test Policy". There should be no wasted time testing policies if everything is not in order.

**Comment by chipzoller** [comment]
I also asked for you to create one PR per error, not one PR total.

**Comment by guohaoyu110** [comment]
> I also asked for you to create one PR per error, not one PR total.

yeah, i know. i will add more PRs later.

**Comment by guohaoyu110** [comment]
> I didn't catch this until now. Move the new step before "Test Policy". There should be no wasted time testing policies if everything is not in order.

you mean put "Validate all policies" before "Test Policy"?

**Comment by chipzoller** [comment]
Yes

**Comment by guohaoyu110** [comment]
please review, this test generate the error as expected and i have changed the new policy from underscore to dashes now. @chipzoller

**Comment by chipzoller** [comment]
Please go ahead with the remainder of the tests.

**Comment by chipzoller** [comment]
Please first open a separate PR which moves the validation step above the first test as discussed.

**Comment by guohaoyu110** [comment]
> Please first open a separate PR which moves the validation step above the first test as discussed.

ok

**Pull request closed without merging**
