### PR TITLE
Fix build issue

### PR DESCRIPTION
**Pull request by vyankyGH**
## Related Issue(s)
closes https://github.com/kyverno/kyverno/issues/3604

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

### CODE REVIEW

**Comment by chipzoller** [comment]
@vyankyGH changing these test to `Fail` is not the right approach as they were previously working with `Skip` which is the intended behavior. I think what we need here is to add [non-existence checks](https://kyverno.io/docs/writing-policies/jmespath/#non-existence-checks). Can you do that instead and see if it works without modifying the tests?

**Comment by vyankyGH** [comment]
> @vyankyGH changing these test to `Fail` is not the right approach as they were previously working with `Skip` which is the intended behavior. I think what we need here is to add [non-existence checks](https://kyverno.io/docs/writing-policies/jmespath/#non-existence-checks). Can you do that instead and see if it works without modifying the tests?

Yup. Will do that

**Comment by vyankyGH** [comment]
@chipzoller I don't think this will get fixed by adding non-existence checks. The response result,  test command getting is _Fail_  instead of skip for all above test cases. this is the reason those test cases getting fail. 
Need to debug more why response changed from Skip to Fail.

**Comment by chipzoller** [comment]
Ok, if it's still failing then we have a CLI code regression somewhere that needs to be identified and fixed.

**Comment by chipzoller** [comment]
Is it ok to close this so the CLI code can be fixed rather than adjusting tests?

**Comment by vyankyGH** [comment]
> Is it ok to close this so the CLI code can be fixed rather than adjusting tests?

Okay. Closing PR.

**Pull request closed without merging**
