### PR TITLE
Simplify Disallow hostPorts in CEL expressions

### LINKED ISSUE #1093: disallow-host-ports: simplify CEL expressions
See: https://github.com/kyverno/policies/issues/1058

### PR DESCRIPTION
**Pull request by lavishpal**
## Related Issue(s)

fixes #1093 

## Description

This PR simplify the CEL expression by removing the repeated terms.

## Checklist

- [] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

### CODE REVIEW

**Comment by lavishpal** [comment]
cc @JimBugwadia

**Review by chipzoller — CHANGES_REQUESTED** [review]
Please see the contribution guide [here](https://github.com/kyverno/policies?tab=readme-ov-file#contribution), specifically the part about modifying Artifact Hub metadata.

**Comment by chipzoller** [comment]
Yes, you need to recalculate the digest of the policy and update the relevant section in the AH metadata file.

**Comment by chipzoller** [comment]
Tests failing.

**Comment by lavishpal** [comment]
Can there be different digest values ​​for same policy?

**Comment by chipzoller** [comment]
If you generate the digest on WIndows versus Linux, yes. The difference in digests come from control characters and line endings. The digests should be generated under Linux or else CI will fail.

**Comment by lavishpal** [comment]
Still getting the different digest value from the value given in  [artifacthub-pkg.yaml](https://github.com/kyverno/policies/blob/main/pod-security-cel/baseline/disallow-host-ports/artifacthub-pkg.yml) of the [file](https://github.com/kyverno/policies/blob/main/pod-security-cel/baseline/disallow-host-ports/disallow-host-ports.yaml) 
OS used : Debian
version : 12

**Comment by chipzoller** [comment]
Ran it in a Code Space, I get the expected digest.

image

**Comment by lavishpal** [comment]
Thank you @chipzoller  for the guidance, now I will quickly update the artifacthub file.

**Review by chipzoller — CHANGES_REQUESTED** [review]
CLI tests now failing after modifications in this policy.

**Comment by lavishpal** [comment]
Closed this pr in favor of #1108

**Pull request closed without merging**
