### PR TITLE
merge: main to release-1.10

### LINKED ISSUE #669: Cherry picks to release-1.10
We need to cherry pick recent test cases and changes to policies etc to the `release-1.10` branch since this is what is used for testing when PRs are made to kyverno/kyverno in the same branch.

cc @mintbomb27

### PR DESCRIPTION
**Pull request by mintbomb27**
## Related Issue(s)
Closes #669 

## Description
Merges `main` to `release-1.10`

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [ ] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [ ] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

### CODE REVIEW

**Comment by chipzoller** [comment]
You may need to force push to get DCO to complete. Also not sure why some CLI tests are failing.

**Comment by chipzoller** [comment]
Seeing failures here:

```
Aggregated Failed Test Cases : 
│───│──────────────────────────────│──────────────────────│──────────────────│────────│
│ # │ POLICY                       │ RULE                 │ RESOURCE         │ RESULT │
│───│──────────────────────────────│──────────────────────│──────────────────│────────│
│ 8 │ set-karpenter-non-cpu-limits │ set-memory           │ test/Pod/test4   │ Fail   │
│ 2 │ add-default-resources        │ add-default-requests │ /Pod/nginx-demo2 │ Fail   │
│───│──────────────────────────────│──────────────────────│──────────────────│────────│
```

**Comment by chipzoller** [comment]
@mintbomb27 let's identify and fix the cause of the CLI failures here.

**Comment by mintbomb27** [comment]
Seems like it was caused by [this commit](https://github.com/kyverno/policies/pull/672/commits/a387ddd541d449eaecc560603162845c4455e5a6) by @MariamFahmy98 . Not sure why that was required. I guess it was for a PR at kyverno/kyverno.

**Comment by chipzoller** [comment]
Thanks!

**Pull request merged**
