### PR TITLE
Update CI workflow

### LINKED ISSUE #242: Test `kyverno/policies:main` against the `kyverno/kyverno:main` CLI
**Describe the bug**
Currently the PRs made against `main` branch of this repo are being tested/checked against the latest [release](https://api.github.com/repos/kyverno/kyverno/releases/latest) CLI build of [kyverno/kyverno](https://github.com/kyverno/kyverno) in the CI workflow. This results in some of the PR checks on this repo getting failed due to some bug fixes/changes that have been introduced to `kyverno/kyverno:main` but haven't been implemented in the latest `release` build.

**Expected behavior**
The `main` branch of this repo should be checked against the `main` branch of [kyverno/kyverno](https://github.com/kyverno/kyverno) in the CI workflow.

**Additional context**
The following PRs have failing build checks due to this issue: https://github.com/kyverno/policies/pull/237 https://github.com/kyverno/policies/pull/241

### PR DESCRIPTION
**Pull request by zeborg**
## Related issue
Closes #242

## Milestone of this PR
`/milestone 1.6.0`

## What type of PR is this
`/kind bug`

## Proposed Changes
PR checks against `main` or `release*` branches will be done through their corresponding [kyverno/kyverno](https://github.com/kyverno/kyverno) branch.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My PR contains new or altered behavior to Kyverno and
- [ ] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.

### CODE REVIEW

**Comment by zeborg** [comment]
@chipzoller review please.

We need to check if it works for `push` events as well, something that can only be done once it's merged to `main` or any `release` branch.

**Review by chipzoller — APPROVED** [review]

**Comment by chipzoller** [comment]
Ok, let me know so I can merge.

**Comment by zeborg** [comment]
@chipzoller Yup, it's working as expected for both `main` and `release` branches 👍

**Comment by chipzoller** [comment]
Cool, merging

**Pull request merged**
