### PR TITLE
Add chainsaw tests for pod-security disallow-proc-mount

### PR DESCRIPTION
**Pull request by jayme-github**
## Description
Based in the kyverno test resources, this adds chainsaw tests for the pod-security and pod-security-cel policy disallow-proc-mount.

For this to work the kind clusters used for e2e testing need to be created with the `ProcMountType` feature gate enabled as `securityContext.procMount` will be forced to `Default` by the apiserver otherwise.

## Checklist
- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
  - not applicable
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.
  - not applicable

### CODE REVIEW

**Review by chipzoller — APPROVED** [review]

**Comment by chipzoller** [comment]
Nice to have tests for these!

**Comment by realshuting** [comment]
This fails the Chainsaw test in [kyverno/kyverno](https://github.com/kyverno/kyverno/actions/runs/9935076627/job/27441075843?pr=10662#step:14:7186):
>    l.go:53: | 07:25:30 | disallow-proc-mount | step-02  | PATCH     | ERROR | v1/Pod @ chainsaw-striking-chamois/badpod01
        === ERROR
        Pod "badpod01" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
          core.PodSpec{
          	Volumes:        {{Name: "kube-api-access-cs7s8", VolumeSource: {Projected: &{Sources: {{ServiceAccountToken: &{ExpirationSeconds: 3607, Path: "token"}}, {ConfigMap: &{LocalObjectReference: {Name: "kube-root-ca.crt"}, Items: {{Key: "ca.crt", Path: "ca.crt"}}}}, {DownwardAPI: &{Items: {{Path: "namespace", FieldRef: &{APIVersion: "v1", FieldPath: "metadata.namespace"}}}}}}, DefaultMode: &420}}}},
          	InitContainers: nil,
          	Containers: []core.Container{
          		{
          			... // 8 identical fields
          			Resources:    {},
          			ResizePolicy: nil,
        - 			VolumeMounts: []core.VolumeMount{
        - 				{
        - 					Name:      "kube-api-access-cs7s8",
        - 					ReadOnly:  true,
        - 					MountPath: "/var/run/secrets/kubernetes.io/serviceaccount",
        - 				},
        - 			},
        + 			VolumeMounts:  nil,
          			VolumeDevices: nil,
          			LivenessProbe: nil,
          			... // 10 identical fields
          		},
          	},
          	EphemeralContainers: nil,
          	RestartPolicy:       "Always",
          	... // 28 identical fields
          }

Checked that the Chainsaw is on 0.2.6 in this repo while kyverno/kyverno uses 0.2.5. 

@eddycharly - is there anything changed in 0.2.6? BTW the Chainsaw upgrade to 0.2.6 failed in kyverno/kyverno.

**Comment by jayme-github** [comment]
@realshuting if this https://github.com/kyverno/kyverno/blob/main/scripts/config/kind/default.yaml is the kind config that is used, it is missing the ProcMountType feature gate (see https://github.com/kyverno/policies/pull/1076/files#diff-8aceeae5c13e78c7714b7ce2bd2249eb0cfd01838602f0efe7b809f0dab5f397). Without that, the apiserver will not force the value `Default` for `securityContext.procMount` which will make the negative tests fail.

**Comment by MariamFahmy98** [comment]
@realshuting - I added the missing feature gate as a part of [this](https://github.com/kyverno/kyverno/pull/10664) PR.

**Pull request merged**
