### PR TITLE
fix: apply policies fixes

### PR DESCRIPTION
**Pull request by eddycharly**
## Related Issue(s)

This PR applies automatic policies fixes.

### CODE REVIEW

**Comment by chipzoller** [comment]
Lots of kuttl failures I see

**Comment by eddycharly** [comment]
I will need to dig this up !

**Comment by eddycharly** [comment]
> changes to policies require recomputing the SHA256 hash and updating the corresponding Artifact Hub metadata file
Do we have an automatic validation for this ?

**Comment by eddycharly** [comment]
@chipzoller i limited the changes to one folder for now

**Review by chipzoller — COMMENTED** [review]
The problem with doing this is these changes are going to set the minimum compatibility to 1.11 which we can't do. The way the website as a front end to the policy library is set up to work is the rendering is done from `main` branch and the annotations are used to filter based on version.

I personally don't see a whole lot of value in this right now but I think the capability behind it is useful.

**Comment by eddycharly** [comment]
@chipzoller why is this going to set the minimum compatibility to 1.11 ?

**Comment by chipzoller** [comment]
You're adding the field `spec.admission` which only exists in 1.11.

**Comment by eddycharly** [comment]
Wasn't this field introduced in 1.10 ?

Ok, this can easily be fixed.

**Comment by chipzoller** [comment]
You're also using title case for `Audit` and `Enforce` which is a version pin to 1.9.

**Comment by eddycharly** [comment]
Hmmm, let's think about it, we should be able to provide up to date policies.

**Comment by chipzoller** [comment]
Two things that would make this more valuable: 1) be able to pass a Kyverno version and have policies updated to the language in that version and 2) run this against the website samples because for those we do always want them to be kept up-to-date with the current release.

**Pull request closed without merging**
