### PR TITLE
add ephemeralContainers to all policies

### PR DESCRIPTION
**Pull request by chrisns**
## Related issue
none
## Milestone of this PR
n/a
## What type of PR is this

/kind feature

## Proposed Changes

Added ephemeralContainers to policies where they aren't already

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] My PR contains new or altered behavior to Kyverno and
- [x] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.

### CODE REVIEW

**Comment by realshuting** [comment]
@chipzoller - can you please help review?

**Comment by chipzoller** [comment]
I'm going to have to think on this one. On the one hand, it's good to include these (and I did think of covering them in the past but ephemeral containers is presently still behind a feature gate), but on the other unless each one of these has been tested and confirmed to work (and the test resources have been included to verify) we really try not to change the policies.

**Comment by chrisns** [comment]
@chipzoller can add to more to more test cases
Though if theres a more repeatable way of articulating `containers|=(initcontainers)|=(ephemeralcontainers)` rather than copy pasting maybe this would be less of an issue (though a different PR to this!)

The current status quo is theres a lot of policy that talks about `initContainers` but the tests often only cover `containers`, I'm keen to not make that problem worse!

Looking forward to your thoughts 😄

**Comment by chipzoller** [comment]
I think we need to prove that the additional modifications do in fact work rather than a copy-and-assume approach. Any help you can offer to cover these with test cases (or just show with some Proof Manifests in individual PRs) would be great. Because that's going to be a lot of work, I would suggest closing this PR for now and breaking these out into individual PRs per policy which gives you time to test on your side and write more test cases.

**Review by chipzoller — COMMENTED** [review]
I think this is too large and hasn't been tested to be generally accepted at this time. The suggestion is to split these out into individual PRs which gives time for testing and further test case development.

**Comment by raesene** [comment]
One thing to note on this is, as of Kubernetes 1.23 ephemeralContainers has progressed to beta and is enabled by default.

**Comment by JimBugwadia** [comment]
@chipzoller - any suggestions on how to decompose and tackle? 

[PSS ](https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline) also includes `ephemeralContainers` so we will need to update accordingly.

**Comment by chrisns** [comment]
in hindsight my pr is probably a fair bit wrong in various places, not all of the fields exist on ephemeral containers, so need to check the actual pod spec. checking won't do any harm obviously, but there is some redundancy

**Comment by chipzoller** [comment]
I'm aware that ephemeralContainers are now on by default, and we do need to address this in the policies. It's just going to take some time to work through them individually and ensure they work as intended as opposed to guessing about their operation based on what may already exist. I don't see another way here than re-touching each policy and verifying the changes have the expected result.

**Comment by chipzoller** [comment]
Also, none of this really matters until Kyverno actually supports ephemeralContainers: https://github.com/kyverno/kyverno/issues/2821

**Comment by chipzoller** [comment]
I've created a temporary repo [here ](https://github.com/chipzoller/kyverno-pss)which includes the current "refresh" of the upstream Pod Security Standard policies for Kyverno and these also address the ephemeral containers. I'll go ahead and close this out but will refer back to it as we keep moving through other pre-existing policies which need ephemeral containers added.

**Pull request closed without merging**
